name: "Deploy to Balena - Draft"

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  build:
    name: "Deploy-to-Balena-Draft"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Deploy to Balena
        uses: balena-io/deploy-to-balena-action@master
        with:
          balena_token: ${{ secrets.BALENA_DRAFT_API_KEY }}
          fleet: ${{ vars.BALENA_DRAFT_FLEET }}
          multi_dockerignore: true
